create database clinic;

\c clinic ;

create table patients(
    id int generated by default as identity primary key,
    name varchar(20),
    date_of_birth date
);

create table medical_histories(
    id int generated by default as identity primary key, 
    admitted_at timestamp, 
    patient_id int references patients(id), 
    status varchar(20)
);

create table treatments(
	id int generated by default as identity primary key, 
	type varchar(20),
	name varchar(20),
	);
  