create database clinic;

\c clinic ;

create table patients(
    id int generated by default as identity primary key,
    name varchar(20),
    date_of_birth date
);

create table medical_histories(
    id int generated by default as identity primary key, 
    admitted_at timestamp, 
    patient_id int references patients(id), 
    status varchar(20)
);

create table treatments(
	id int generated by default as identity primary key, 
	type varchar(20),
	name varchar(20),
	);

CREATE TABLE treatment_histories (
    treatment_id INT NOT NULL,
    medical_history_id INT NOT NULL,
    PRIMARY KEY (treatment_id, medical_history_id),
    CONSTRAINT fk_treatments FOREIGN KEY (treatment_id) REFERENCES treatments(id),
    CONSTRAINT fk_medical_histories FOREIGN KEY (medical_history_id) REFERENCES medical_histories(id)
);

CREATE TABLE invoices (
	id int generated by default as identity primary key,
	total_amount decimal,
	generated_at timestamp,
	payed_at timestamp,
	medical_history_id int REFERENCES medical_histories(id)
);

create table invoice_items (
	id int generated by default as identity primary key,
	unit_price decimal,
	quantity int,
	total_price decimal,
	invoice_id int REFERENCES invoices(id),
	treatment_id int REFERENCES treatments(id)
);
